name: Web Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [closed]
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.2

    #setup gradlew
    - name: gradlew
      run : chmod +x gradlew

    #execute gradle command for running cucumber test
    - name: Execute Test
      run : ./gradlew cucumber
